### ISSUE TITLE
add CONTRIBING.md

### ISSUE THREAD

**Issue by dericed** [Matroska-Org/matroska-specification#14]
I suggest adding a CONTRIBUTING.md file to promote contribution, explain what is happening in this repo, and reference the Cellar working group. Possibly we could add some issues suitable to new contributors.

I can't assign in this repo, but will at @ablwr anyway.

**Comment by ablwr** [comment]
I can generate a file using `[Octohatrack](https://github.com/LABHR/octohatrack)` which compiles a list of code contributors as well as people opening issues and providing helpful comments.

**Comment by ablwr** [comment]
It was lackluster because this repo is pretty new. In my open PR #15, I converted the existing Contributing page over to Markdown: https://github.com/Matroska-Org/matroska-specification/pull/15/commits/13c55d9ef6832d6a580d1dec67c0c2e3f26bed36 

We can keep the syntax as it is there, we can replace it with a contributing.md, or some combination or something else?

**Comment by dericed** [comment]
I think this is closed via https://github.com/Matroska-Org/matroska-specification/blob/gh-pages/contributions.md
