### ISSUE TITLE
Specify PCM signedness

### ISSUE THREAD

**Issue by mkver** [Matroska-Org/matroska-specification#142]
Hello,

currently, for PCM tracks only the endianess (via Codec ID), the channel count, the sampling frequency and the bitdepth (via the audio header elements) are explicitly stored; the signedness is not so that it is completely unspecified and hence ambiguous. This should be changed. Given that 8-bit PCM is usually unsigned while the higher bitdepths are usually signed (that is how it is done in wav), we should specify it as such. This is also how FFmpeg treats 8-bit audio inside Matroska.

Greetings
Andi

**Comment by dericed** [comment]
Thanks for pointing this out. How about a phrase to each PCM definition such as:
> Audio samples MUST be considered as signed values, except if the audio bit depth is `8` which MUST be interpreted as unsigned values.

I suppose we should consider how to make Matroska a bit more explicate so that signedness could be stated rather than inferred.

Also, I'm not enough familiar with floats in PCM, but is this exception relevant to PCM as Float. I can't find an example of an 8 bit floating point. It sounds silly, but I suppose the except should be consistent.

**Comment by mkver** [comment]
I have never ever heard of 8bit float (and ffmpeg doesn't support it either). Therefore I can't answer your question. Sorry.

**Comment by dericed** [comment]
@mkver please review https://github.com/Matroska-Org/matroska-specification/commit/5dedfc82a92dd707382fa74ceb48b6323466415b which is merged. If ok, please close this issue.
