### ISSUE TITLE
Fix internal documentation links

### ISSUE THREAD

**Issue by robUx4** [Matroska-Org/matroska-specification#145]
Right now the Markdown code has a lot of `{{site.baseurl}}/index.html#Cluster` links. But they fail to link properly in the code.
I'm not sure how to fix this properly. Also I'm not sure it is good pratice to put links inside an RFC at all.

**Comment by ablwr** [comment]
This, too, is tied to my response to the `layout: default` issue you brought up on the CELLAR list: measures taken to automatically build and replicate the HTML structure.

**Comment by ablwr** [comment]
I see that the link you are referring to, specifically, no longer links to anything, anyway. We should remove the broken ones.

Intra-document links sometimes work in the generated html, if formatted correctly (all lowercase, swapping spaces for hyphens). But, like our other conversations about this subject -- the most important source is the generated RFC, not the website.

I think it's best to remove the links for now, also because the document is in flux and some headers cease to exist, some new ones spring up, and others change. This would break the existing links and cause extra confusion!

**Comment by ablwr** [comment]
I will go through and update the links accordingly. If it's an intra-document link created just to be helpful, I will remove it. If it's a regular link, I will leave it. If it's an intra-document like that is phrased in a "See [this]", I will do my best to keep it.

**Comment by robUx4** [comment]
Fixed
